
documents = [
    {"title": "R1 Short title, applicability and commencement", "link": "https://docs.google.com/document/d/1X-TEUSA3of06h0FEpTRp-0X6Q6Ial9um/edit"},
    {"title": "R2 Definitions", "link": "https://docs.google.com/document/d/1Uv2xo-C0Uv5qy74MS6gOkXzY3lBx85HF/edit"},
    {"title": "R3 Applicability", "link": "https://docs.google.com/document/d/1JUCUI1Z7k1_SxIvZR1k4Ez_97vjP3zbU/edit"},
    {"title": "R4 DRAWINGS, PERMITS AND OCCUPANCY CERTIFICATES", "link": "https://docs.google.com/document/d/1rQoJmBRa8aK3Q1Y2oAM43_7-lHEkzi4j/edit"},
    {"title": "R5 Application for development / building permit", "link": "https://docs.google.com/document/d/1UtQeXhJ0HiyuDSfM2Im0OiEqnSPj90v6/edit"},
    {"title": "R6 Plans to be submitted", "link": "https://docs.google.com/document/d/1vCCNztAimcQQCxqUNVHA-2sGvqpW2J7u/edit"},
    {"title": "R7 Certain operational constructions by Government to be exempted from these rules", "link": "https://docs.google.com/document/d/19SlPVnOvx_sLVa1vGkQcgQRtZlCZX2Wh/edit"},
    {"title": "R8 Permit not necessary for certain works", "link": "https://docs.google.com/document/d/1KAbVJwaUZNubHNqBwhfeSQsPqiocm9h-/edit"},
    {"title": "R9 Approval of site and plans and issue of permit", "link": "https://docs.google.com/document/d/1g6vgoejoRhiWKGX8WgbA5cx04HFUEIdd/edit"},
    {"title": "R10 Approval of site and plans and issue of permit where excavations to a depth of more than 1.5M", "link": "https://docs.google.com/document/d/1cJGq_dg4uhAaShImJXA9_jRb-gLiajaP/edit"},
    {"title": "R11 Grounds on which approval of site or permission to construct or reconstruct building may be rejected", "link": "https://docs.google.com/document/d/1z3mtHghA8ZJ115NE13M1etKVVh19a9Hv/edit"},
    {"title": "R12 Period within which approval or disapproval shall be intimated", "link": "https://docs.google.com/document/d/1M5VlLEfJouO2nFjnqN7G1jJrAdydYI6e/edit"},
    {"title": "R13 Period within which Secretary is to grant or refuse permission to execute work", "link": "https://docs.google.com/document/d/1g1kylyGEMPrMmMWxy_TrOGFXngPWzMcc/edit"},
    {"title": "R14 Reference to Council where the Secretary delays to grant or refuse or approve permit", "link": "https://docs.google.com/document/d/1PJnWQY97zS8eWrtY2CNXLSHxGDrV54u4/edit"},
    {"title": "R15 Extension and renewal of period of permits", "link": "https://docs.google.com/document/d/1bRVdr4HHoKati1m7dYZiPXuc1LABq6i8/edit"},
    {"title": "R16 Suspension and Revocation of permit", "link": "https://docs.google.com/document/d/1iBo0gs_WFhk9PtYseXlgGNogkEKqoGnD/edit"},
    {"title": "R17 Duties and responsibilities of the owner or developer", "link": "https://docs.google.com/document/d/1XgOs2Kt6Po6dh7PSGy-D4DjGZjQ_-OT7/edit"},
    {"title": "R18 Responsibilities and functions of registered Architects, etc", "link": "https://docs.google.com/document/d/1oeyx6B5gn-CW1fZ4bHAs6PaoLQ9p__xV/edit"},
    {"title": "R19 Transfer of plots to be intimated", "link": "https://docs.google.com/document/d/1Ur-ZjE_CTsQC4004vUW5MeQiMLodqr7Z/edit"},
    {"title": "R19A Procedure for grant of acknowledgement certificate", "link": "https://docs.google.com/document/d/1sLH9f_Kq9M-LtfqiXY3UpNocHfrMHDuE/edit"},
    {"title": "R19B Other conditions pertaining to self certification", "link": "https://docs.google.com/document/d/1T9ucyEr92RYpQMkGWcbtOiL2HjgV9i_I/edit"},
    {"title": "R19C Issue of occupancy certificate", "link": "https://docs.google.com/document/d/1ELknFVL479VN3tzvcDxRt19ujZovtcEE/edit"},
    {"title": "R19D Procedure for plinth level inspection for low-risk buildings", "link": "https://docs.google.com/document/d/11xZ9bil_CbZuTUnnldKy8eQRKxP9nHi6/edit"},
    {"title": "R19E Procedure for plinth level inspection for all other buildings", "link": "https://docs.google.com/document/d/1QB21Ub6dXHScOMGhdVuun5grfsC1Ucpy/edit"},
    {"title": "R19F Deemed completion of plinth level inspection", "link": "https://docs.google.com/document/d/1zEulx7AOD6fmM1STR-kc877OgL4A8Ba0/edit"},
]
